### ISSUE TITLE
I noticed that in unread messages the labes get displayed wrong

### ISSUE THREAD

**Issue by ntimo** [scastiel/pm-inbox-theme#2]
Hi their,
when you have a unread message that also has a label it gets displayed like this: 
<img width="159" alt="bildschirmfoto 2017-02-02 um 06 31 43" src="https://cloud.githubusercontent.com/assets/6145026/22566515/7b0f66ec-e98c-11e6-893b-9b393d316336.png">

It would be really really cool if you could fix this. Because your theme is absolutly amazing!

Timo

**Comment by scastiel** [comment]
@ntimo it's fixed :smile:

**Comment by ntimo** [comment]
@scastiel thanks :) You are awesome!
